FROM alpine:latest
ENV PYTHONUNBUFFERED 1

# Add system dependencies
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev make

# Allows docker to cache installed dependencies between builds
COPY Pipfile* ./
RUN pip install pipenv
RUN pipenv install --dev --system --deploy --ignore-pipfile

# Adds our application code to the image
COPY . /code/
WORKDIR /code

# Expose Django's port
EXPOSE $PORT
